# Generated by Django 4.0.5 on 2022-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataText', models.CharField(max_length=100)),
                ('algo', models.CharField(choices=[('naive', 'NAIVE'), ('logistic', 'LOGISTIC'), ('decision', 'DECISION'), ('knn', 'KNN'), ('svm', 'SVM')], default=' ', max_length=200)),
            ],
        ),
    ]
