# Generated by Django 4.0.5 on 2022-06-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='algo',
            field=models.CharField(choices=[('naive', 'NAIVE'), ('logistic', 'LOGISTIC'), ('decision', 'DECISION'), ('knn', 'KNN'), ('svm', 'SVM'), ('Rf', 'RandomForest')], default=' ', max_length=200),
        ),
    ]
